# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Python package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish@v1.8
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
        poetry_version: "==1.2.0a2"
